[[dependency]]
python = "../../_build/target-deps/python"
packages = [
    "miskeyed-xr-agent==0.1.0",
]
target = "../../_build/target-deps/pip_prebundle"
platforms = ["*"]
download_only = false
append_to_install_folder = true

